---
- name: Delivery
  hosts: localhost
  tags: delivery 
  tasks:
    - name: Login to Docker Hub
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Build Docker Image
      community.docker.docker_image:
        name: "taifalsubaie/test2:{{ build_version }}"
        source: build
        build:
          path: .

    - name: Push Docker Image -> docker hub
      community.docker.docker_image:
        name: "taifalsubaie/test2:{{ build_version }}"
        push: true
        source: local

    - name: Tag and Push Docker Image -> nexus
      community.docker.docker_image:
        name: "taifalsubaie/test2:{{ build_version }}"
        repository: "35.181.65.18:8082/react"
        tag: "{{ build_version }}"
        push: true
        source: local

- name: Deploy to docker
  hosts: docker_servers
  become: true
  tags: deploy 
  tasks:
    - name: Pull an image
      community.docker.docker_image:
        name: "taifalsubaie/test2:{{ build_version }}"
        source: pull

    - name: Remove old container
      community.docker.docker_container:
        name: react-test
        state: absent

    - name: Run container
      community.docker.docker_container:
        name: react-test
        image: "taifalsubaie/test2:{{ build_version }}"
        state: started
        recreate: true
        published_ports:
          - "8086:80"
